/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDCard.h"
#include "SDCard_SPI.h"
#include "SDCard_FS.h"
#include "SDCard_SPIM.h"
#include "SDCard_SPIM_SPI_UART.h"
#include "SDCard_SPIM_PINS.h"
#include "SDCard_SPIM_SPI_UART_PVT.h"
#include "SDCard_SPIM_PVT.h"
#include "SDCard_SPIM_BOOT.h"
#include "SDCard_SD_Clock.h"
#include "SDCard_SD_PWR.h"
#include "SDCard_SD_PWR_aliases.h"
#include "SDCard_SD_CS.h"
#include "SDCard_SD_CS_aliases.h"
#include "SDCard_SD_WP.h"
#include "SDCard_SD_WP_aliases.h"
#include "SDCard_SD_CD.h"
#include "SDCard_SD_CD_aliases.h"
#include "SDCard_SPIM_sclk_m.h"
#include "SDCard_SPIM_sclk_m_aliases.h"
#include "SDCard_SPIM_miso_m.h"
#include "SDCard_SPIM_miso_m_aliases.h"
#include "SDCard_SPIM_mosi_m.h"
#include "SDCard_SPIM_mosi_m_aliases.h"
#include "SDCard_SPIM_ss0_m.h"
#include "SDCard_SPIM_ss0_m_aliases.h"
#include "SDCard_SPIM_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

